version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "main"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
    # No ignore rules - get notifications for all dependency updates
    commit-message:
      prefix: "deps"
      include: "scope"
    # Only update direct dependencies (not transitive sub-dependencies)
    allow:
      - dependency-type: "direct"
    # Group all Python updates into a single PR
    groups:
      python-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      # Separate group for major version updates (require more attention)
      python-major-updates:
        patterns:
          - "*"
        update-types:
          - "major"

  # Docker base image updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "main"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "deps"
      include: "scope"

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "main"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "*"
