version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "main"
    labels:
      - "dependencies"
      - "python"
    # No ignore rules - get notifications for all dependency updates
    commit-message:
      prefix: "deps"
      include: "scope"
    # Only update direct dependencies (not transitive sub-dependencies)
    allow:
      - dependency-type: "direct"
    # Group all Python updates into a single PR
    groups:
      python-dependencies:
        patterns:
          - "*"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "github-actions"
    # Group all GitHub Actions updates into a single PR
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
